'use client';

import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { useState } from "react";

import Navbar from "./ui/navbar";
import "./globals.css";
import { inter } from '@/app/ui/fonts';
import '@/app/globals.css';
import Popup from "./ui/popup";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export const experimental_ppr = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [popupMessage, setPopupMessage] = useState<string | null>(null);

  return (
    <html lang="en">
      <SessionProvider>
      <body className={`${inter.className} antialiased`}>
          <div className="w-full flex">
            <Navbar setPopupMessage={setPopupMessage} /> {/* Popup-Nachricht von der Navbar aus setzen */}
          </div>
          {popupMessage && <Popup message={popupMessage} />} {/* Zeige das Popup an, wenn eine Nachricht gesetzt ist */}
          <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
        </body>
      </SessionProvider>
    </html>
  );
}
