import type { Metadata } from "next";
import Navbar from "./ui/navbar";

import "./globals.css";
import { inter } from '@/app/ui/fonts';
import '@/app/globals.css';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const experimental_ppr = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        
        <Navbar />
        
        <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
      </body>
    </html>
  );
}
